movieproject/movieapp/urls.py
from .import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name="add_movie"),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL,
            document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    name=models.CharField(max_length=250)
    description=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
def __str__(self):
    return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import movies
class movie_form(forms.ModelForm):
    class Meta:
        model=movies
        fields=['name','description','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import movie_form
from  .models import movies


# Create your views here.
def index(request):
    movie=movies.objects.all()
    context={
        'movie_list':movie
    }
    return  render(request,'index.html',context)

def detail(request,movie_id):
    movie=movies.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})
# return HttpResponse("this is movie no %s" %movie_id)
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        description = request.POST.get('description', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie=movies(name=name,description=description,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=movies.objects.get(id=id)
    form=movie_form(request.POST or None,request.FILES,instance=movie)
    if form .is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Title</title>-->
<!--</head>-->
<!--<body>-->
{% extends 'base.html' %}
{% block body %}
<Form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your movie name"><br>
    <input type="text" name="description" placeholder="explain movie in detail"><br>
    <input type="text" name="year" placeholder="year of release">
    <br><input type="file" name="img"><br>
    <input type="submit" >
    {% endblock %}

</Form>
<!--</body>-->
<!--</html>-->

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store

  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>delete</title>
</head>
<body>
<form method="post">
  {% extends 'base.html' %}
{% block body %}
  {% csrf_token %}
  Are you sure?
  <input type="submit">
  {% endblock %}
</form>
</body>
</html>

movieproject/templates/detail.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Home</title>-->
<!--</head>-->
<!--<body>-->
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
      <img src="{{movie.img.url}}" width="600" height="200">
        </div>
    </div>

<div class="col-md-6">
   <h2>{{movie.name}}</h2>
    <h6>{{movie.description}}</h6>
    <h6>{{movie.year}}</h6>
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}"> Delete</a>
</div>
</div>
{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
 {% endblock %}
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3"></div>
        <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="450px" height="200px;">
  <div class="card-body">
    <h5 class="card-title"> {{i.name}}</h5>
    <p class="card-text"> {{i.description}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View details</a>
  </div>
        </div>
        {% endfor %}
    </div>

</div>
<!--<img src="{{i.img.url}}" width="300" height="200">-->
<!--&lt;!&ndash;<a href="movie/{{i.id}}">{{i.name}}<br>&ndash;&gt;-->

<!--{{i.description}}.......-->
<!--{{i.year}}-->

{% endblock %}